services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"

    deploy:
      replicas: 4
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
